[package]
name = "rusty_roguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
# ECS
legion = "=0.3.1"

[profile.release]
# Enable link-time optimization
lto = "thin"
